<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p0rY3uv' shared service.

return $this->privates['.service_locator.p0rY3uv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'encoder' => array('services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true),
    'menager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
));
