<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oGpW2Sj' shared service.

return $this->privates['.service_locator.oGpW2Sj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'menager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
    'user' => array('privates', '.errored..service_locator.oGpW2Sj.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.oGpW2Sj": it references class "App\\Entity\\User" but no such service exists.'),
));
