<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKg2xFNx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKg2xFNx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKg2xFNx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKg2xFNx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKg2xFNx\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Kg2xFNx',
    'container.build_id' => 'ce252ba6',
    'container.build_time' => 1544017895,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKg2xFNx');
