<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7MJY4i7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7MJY4i7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7MJY4i7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7MJY4i7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7MJY4i7\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '7MJY4i7',
    'container.build_id' => 'cb971a4e',
    'container.build_time' => 1544096573,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7MJY4i7');
